name: Release
on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build release
        run: cargo build --release
      - name: Prepare binary
        run: |
          mkdir -p dist
          cp target/release/pgquerymon dist/pgquerymon-linux
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgquerymon-linux
          path: dist/pgquerymon-linux

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build release
        run: cargo build --release
      - name: Prepare binary
        run: |
          mkdir dist
          copy target\release\pgquerymon.exe dist\pgquerymon-windows.exe
        shell: pwsh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgquerymon-windows.exe
          path: dist/pgquerymon-windows.exe

  upload-release:
    name: Upload Release Assets
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: pgquerymon-linux
          path: dist
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: pgquerymon-windows.exe
          path: dist
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

