name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build release
        run: cargo build --release

      - name: Rename binary for upload
        run: |
          mkdir -p dist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp target/release/npgsql-mon.exe dist/npgsql-mon-windows.exe
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp target/release/npgsql-mon dist/npgsql-mon-macos
          else
            cp target/release/npgsql-mon dist/npgsql-mon-linux
          fi
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

