name: Release

on:
  release:
    types: [published]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build release
        run: cargo build --release
      - name: Prepare binary
        run: |
          mkdir -p dist
          cp target/release/npgsql-mon dist/npgsql-mon-linux
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: npgsql-mon-linux
          path: dist/npgsql-mon-linux

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build release
        run: cargo build --release
      - name: Prepare binary
        run: |
          mkdir dist
          copy target\release\npgsql-mon.exe dist\npgsql-mon-windows.exe
        shell: pwsh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: npgsql-mon-windows.exe
          path: dist/npgsql-mon-windows.exe

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build release
        run: cargo build --release
      - name: Prepare binary
        run: |
          mkdir -p dist
          cp target/release/npgsql-mon dist/npgsql-mon-macos
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: npgsql-mon-macos
          path: dist/npgsql-mon-macos

  upload-release:
    name: Upload Release Assets
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: npgsql-mon-linux
          path: dist
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: npgsql-mon-windows.exe
          path: dist
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: npgsql-mon-macos
          path: dist
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

